--3.1
select * from ORDERS
WHERE ORDER_DATE BETWEEN '2007-01-01' and '2008-01-01'

--3.2
SELECT * from SALESREPS
where MANAGER is null;

--3.3
select * from OFFICES
where REGION like 'East%';

--3.4
select * from ORDERS
where AMOUNT > 10000
ORDER by AMOUNT desc;

--3.5
SELECT NAME, HIRE_DATE
FROM SALESREPS
ORDER BY AGE;

--3.6
select * from ORDERS
order by amount desc, qty asc;

--3.7
select * from ORDERS
order by AMOUNT DESC
LIMIT 5;

--3.8
SELECT * from CUSTomers
ORDER by CREDIT_LIMIT DESC
LIMIT 11;

--3.9
select * from SALESREPS
order by HIRE_DATE
LIMIT 3,4

--3.10
SELECT *
FROM SALESREPS
WHERE AGE IN (
    SELECT AGE
    FROM SALESREPS
    ORDER BY AGE
    LIMIT 3, 4
)
ORDER BY AGE;

--3.11
select DISTINCT * from ORDERS;

--3.12
select cust, count(*) as AMOUNT 
from ORDERS
GROUP by cust;

--3.13
SELECT REP, AVG(AMOUNT) AS AVG_PRICE
FROM ORDERS
GROUP BY REP;

--3.14
select DISTINCT NAME
from ORDERs
inner join SALESREPS ON ORDERS.REP = SALESREPS.EMPL_NUM
where ORDErs.AMOUNT > 10000;

--3.15
select MFR_ID, count(*) as AMOUNT
from PRODUCTs
group by MFR_ID;

--3.16
select MFR_ID,max(price) as MAX_PRICE 
from PRODUCTS
group by MFR_ID;


--3.17
SELECT c.COMPANY, p.DESCRIPTION, p.MFR_ID, o.QTY, o.AMOUNT
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUST_NUM = o.CUST
JOIN PRODUCTS p ON o.MFR = p.MFR_ID AND o.PRODUCT = p.PRODUCT_ID;

--3.18
SELECT *
FROM SALESREPS
WHERE EMPL_NUM NOT IN (
    SELECT DISTINCT REP
    FROM ORDERS
);

--3.19


SELECT *
FROM SALESREPS
WHERE AGE IN (
    SELECT AGE
    FROM SALESREPS
    GROUP BY AGE
    HAVING COUNT(*) > 1
);

--3.20
select DESCRIPTION
from ORDERS inner join CUSTOMERS on CUST = CUST_NUM
inner join PRODUCTS on PRODUCT = PRODUCT_ID
where company = 'First Corp.';

--3.21
select * from ORDERS
where AMOUNT > (select avg(amount) from ORDERS);

--3.22
SELECT DISTINCT s.NAME
FROM SALESREPS s
JOIN CUSTOMERS c1 ON s.EMPL_NUM = c1.CUST_REP
JOIN CUSTOMERS c2 ON c1.CUST_NUM = c2.CUST_NUM AND s.EMPL_NUM <> c2.CUST_REP;

--3.23
SELECT Cust
FROM ORDERS
WHERE ORDER_DATE IN (
    SELECT ORDER_DATE
    FROM ORDERS
    GROUP BY ORDER_DATE
    HAVING COUNT(*) > 1
);


--3.24
select REP_OFFICE, sum(AMOUNT) as AMOUNT_SALES
from ORDERS inner join  SALESREPS on EMPL_NUM = rep
group by REP_OFFICE
having REP_OFFICE is not null
order by AMOUNT_SALES desc


--3.25
select * from SALESREPS;

select name FROM SALESREPS
where MANAGER is not null;


--3.26
select EMPL_NUM, name from SALESREPS
where EMPL_NUM not in (
select MANAGER from SALESREPS );



SELECT *
FROM SALESREPS
WHERE EMPL_NUM NOT IN (
    SELECT DISTINCT MANAGER
    FROM SALESREPS
);

--3.27
select * from OFFICES;
select * from ORDERS;
select * from SALESREPS;

select DESCRIPTION
from ORDERS
inner join SALESREPS on EMPL_NUM = REP
inner JOIN
OFFICES on REP_OFFICE = OFFICE
inner join PRODUCTS on ORDERS.PRODUCT = PRODUCTS.PRODUCT_ID
where REGION = 'Western'


--3.28
select name, HIRE_DATE, SALES
from SALESREPS
order by sales;

--3.29
select ORDERs.*
from ORDERS
inner join SALESREPS on EMPL_NUM = REP
inner JOIN
OFFICES on REP_OFFICE = OFFICE
inner join PRODUCTS on ORDERS.PRODUCT = PRODUCTS.PRODUCT_ID
where REGION = 'Eastern'
ORDER by qty


--3.30
select * from ORDERS
where AMOUNT > (
select avg(AMOUNT)
from ORDERS INNER join CUSTOMERS on ORDERs.CUST = CUSTOMERS.CUST_NUM
where COMPANY = 'First Corp.');


--3.31
select ORDERS.*
from ORDERS INNER join CUSTOMERS on ORDERs.CUST = CUSTOMERS.CUST_NUM
where COMPANY = 'First Corp.';

--3.32

SELECT c.CUST_NUM, p.PRODUCT_ID, p.DESCRIPTION, p.PRICE
FROM PRODUCTS p
JOIN ORDERS o ON p.MFR_ID = o.MFR AND p.PRODUCT_ID = o.PRODUCT
JOIN CUSTOMERS c ON o.CUST = c.CUST_NUM
WHERE p.PRICE < (
    SELECT AVG(p2.PRICE)
    FROM PRODUCTS p2
    JOIN ORDERS o2 ON p2.MFR_ID = o2.MFR AND p2.PRODUCT_ID = o2.PRODUCT
    WHERE o2.CUST = c.CUST_NUM
)

--3.33
SELECT DISTINCT s.NAME
FROM SALESREPS s
JOIN ORDERS o1 ON s.EMPL_NUM = o1.REP
WHERE o1.ORDER_DATE LIKE '2008%'
AND NOT EXISTS (
    SELECT 1
    FROM ORDERS o2
    WHERE o2.REP = s.EMPL_NUM
    AND o2.ORDER_DATE LIKE '2007%'
);

SELECT DISTINCT s.NAME
FROM SALESREPS s
JOIN ORDERS o1 ON s.EMPL_NUM = o1.REP AND o1.ORDER_DATE LIKE '2008%'
LEFT JOIN ORDERS o2 ON s.EMPL_NUM = o2.REP AND o2.ORDER_DATE LIKE '2007%'
WHERE o2.ORDER_NUM IS NULL;


--3.34
SELECT DISTINCT s.NAME
FROM SALESREPS s
JOIN ORDERS o1 ON s.EMPL_NUM = o1.REP
WHERE o1.ORDER_DATE LIKE '2007%'
AND NOT EXISTS (
    SELECT 1
    FROM ORDERS o2
    WHERE o2.REP = s.EMPL_NUM
    AND o2.ORDER_DATE LIKE '2008%'
);

SELECT DISTINCT s.NAME
FROM SALESREPS s
JOIN ORDERS o1 ON s.EMPL_NUM = o1.REP AND o1.ORDER_DATE LIKE '2007%'
LEFT JOIN ORDERS o2 ON s.EMPL_NUM = o2.REP AND o2.ORDER_DATE LIKE '2008%'
WHERE o2.ORDER_NUM IS NULL;


--3.35
SELECT c.COMPANY
FROM CUSTOMERS c
WHERE EXISTS (
    SELECT 1
    FROM ORDERS o1
    WHERE o1.CUST = c.CUST_NUM AND o1.ORDER_DATE LIKE '2008%'
)
AND EXISTS (
    SELECT 1
    FROM ORDERS o2
    WHERE o2.CUST = c.CUST_NUM AND o2.ORDER_DATE LIKE '2007%'
)
INTERSECT
SELECT c.COMPANY
FROM CUSTOMERS c
WHERE EXISTS (
    SELECT 1
    FROM ORDERS o3
    WHERE o3.CUST = c.CUST_NUM AND o3.ORDER_DATE LIKE '2008%'
)
AND EXISTS (
    SELECT 1
    FROM ORDERS o4
    WHERE o4.CUST = c.CUST_NUM AND o4.ORDER_DATE LIKE '2007%'
);



SELECT c.COMPANY
FROM CUSTOMERS c
JOIN ORDERS o ON c.CUST_NUM = o.CUST
WHERE strftime('%Y', o.ORDER_DATE) = '2008'
      AND c.COMPANY IN (
          SELECT c2.COMPANY
          FROM CUSTOMERS c2
          JOIN ORDERS o2 ON c2.CUST_NUM = o2.CUST
          WHERE strftime('%Y', o2.ORDER_DATE) = '2007'
      )
GROUP BY c.COMPANY;
